-- MySQL Script generated by MySQL Workbench
-- Sat Jun  1 23:22:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `position` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `isbn` VARCHAR(13) NULL DEFAULT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `author` VARCHAR(100) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `publication_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`isbn`));


-- -----------------------------------------------------
-- Table `mydb`.`Date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Date` (
  `epoch_date` BIGINT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `day` INT NULL DEFAULT NULL,
  `month` INT NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `is_holiday` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`epoch_date`));


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `order_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `order_epoch_date` BIGINT NULL DEFAULT NULL,
  `order_timestamp` TIMESTAMP NOT NULL,
  `total_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX (`customer_id` ASC) VISIBLE,
  INDEX (`order_epoch_date` ASC, `order_timestamp` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`),
  CONSTRAINT ``
    FOREIGN KEY (`order_epoch_date` , `order_timestamp`)
    REFERENCES `mydb`.`Date` (`epoch_date` , `timestamp`));


-- -----------------------------------------------------
-- Table `mydb`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sales` (
  `sales_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `isbn` VARCHAR(13) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `unit_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_price` DECIMAL(10,2) GENERATED ALWAYS AS (quantity * unit_price),
  PRIMARY KEY (`sales_id`),
  INDEX (`order_id` ASC) VISIBLE,
  INDEX (`isbn` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`Order` (`order_id`),
  CONSTRAINT ``
    FOREIGN KEY (`isbn`)
    REFERENCES `mydb`.`Book` (`isbn`));


-- -----------------------------------------------------
-- Table `mydb`.`Shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shift` (
  `shift_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `employee_id` INT NULL DEFAULT NULL,
  `epoch_date` BIGINT NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `shift_type` ENUM('morning', 'evening') NULL DEFAULT NULL,
  PRIMARY KEY (`shift_id`),
  INDEX (`employee_id` ASC) VISIBLE,
  INDEX (`epoch_date` ASC, `timestamp` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employee` (`employee_id`),
  CONSTRAINT ``
    FOREIGN KEY (`epoch_date` , `timestamp`)
    REFERENCES `mydb`.`Date` (`epoch_date` , `timestamp`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
